# This workflow will install Python dependencies and run some static tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  python-version: "3.11"
  pyinstaller-version: "6.6"
  project-name: the-stars-came-down-screaming

jobs:
  build:
    # PyInstaller will generate an executable for the platform it is run on,
    # so we must run the workflow on all three platforms.
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller==6.6
          pip install -r requirements.txt  # Install project dependencies

      - name: Build project
        run: pyinstaller build.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TSCDS-${{ github.run_number }}-${{ matrix.os }}  # Name the artifact
          path: dist/the_stars_came_down_screaming/
